"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const JSONIO_1 = require("./JSONIO");
const Graph_1 = require("./Graph");
const DistanceGraph_1 = require("./DistanceGraph");
const inputFileName = 'miserables';
const ego = 'Valjean';
const data = JSONIO_1.JSONIO.rescaleEdges(JSONIO_1.JSONIO.readObjectsFromJSON(inputFileName + ".edges.json", "data"));
console.log(data);
const graph = new Graph_1.Graph(data);
const distanceGraph = new DistanceGraph_1.DistanceGraph(graph);
distanceGraph.computeDijkstraDistances(ego);
const egoNodes = distanceGraph.getEgocentricDistances(ego);
const edgeList = distanceGraph.EdgeList;
const annotatedEdges = distanceGraph.getAnnotatedEdges(ego);
JSONIO_1.JSONIO.writeObjectsToJSON(egoNodes, inputFileName + ".nodes.json", "./data");
JSONIO_1.JSONIO.writeObjectsToJSON(annotatedEdges, inputFileName + ".annotated.edges.json", "./data");
console.log(egoNodes);
console.log(edgeList);
console.log(annotatedEdges);
