"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const JSONIO_1 = require("./JSONIO");
const Graph_1 = require("./Graph");
const DistanceGraph_1 = require("./DistanceGraph");
const data = JSONIO_1.JSONIO.readObjectsFromJSON("simple.edges.json", "data");
const graph = new Graph_1.Graph(data);
const distanceGraph = new DistanceGraph_1.DistanceGraph(graph);
distanceGraph.computeDijkstraDistances("0");
const egoNodes = distanceGraph.getEgocentricDistances("0");
const edgeList = distanceGraph.EdgeList;
const annotatedEdges = distanceGraph.getAnnotatedEdges();
JSONIO_1.JSONIO.writeObjectsToJSON(egoNodes, "simple.nodes.json", "./data");
JSONIO_1.JSONIO.writeObjectsToJSON(annotatedEdges, "simple.annotated.edges.json", "./data");
console.log(egoNodes);
console.log(edgeList);
console.log(annotatedEdges);
